### PR TITLE
Add nodejs 8 support and use this version by default

### PR DESCRIPTION
**Pull request by agherzan**

### CODE REVIEW

**Review by CameronDiver — APPROVED** [review]

**Comment by CameronDiver** [comment]
add to whitelist

**Comment by mikesimos** [comment]
@resin-jenkins test this please

**Comment by CameronDiver** [comment]
@resin-jenkins test this please

**Comment by CameronDiver** [comment]
@resin-ci retest

**Comment by CameronDiver** [comment]
@resin-jenkins add to whitelist

**Comment by CameronDiver** [comment]
@resin-jenkins test this please

**Comment by CameronDiver** [comment]
@resin-ci retest

**Pull request merged**
